version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: thejuniorsmind-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: thejuniorsmind
      MYSQL_USER: thejuniorsmind
      MYSQL_PASSWORD: thejuniorsmind
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  adminer:
    image: adminer
    container_name: thejuniorsmind-adminer
    restart: unless-stopped
    ports:
      - "8081:8080"

volumes:
  db_data:
